# Generated by Django 3.2.9 on 2021-11-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20211130_2324'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='clothes.clothes')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='order.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
