# Generated by Django 3.2.9 on 2021-11-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20211130_2324'),
        ('order', '0002_auto_20211130_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclothes',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_clothes', to='clothes.clothes'),
        ),
        migrations.AlterField(
            model_name='orderclothes',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_clothes', to='order.order'),
        ),
    ]
