# Generated by Django 3.2.9 on 2021-11-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_like_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_c', to='clothes.clothes'),
        ),
    ]
