# Generated by Django 3.2.9 on 2021-11-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothesimage_clothes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='title',
            new_name='type_of_clothes',
        ),
    ]
