# Generated by Django 3.2.9 on 2021-11-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_saved_clothes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='review',
            new_name='comment',
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
