# Generated by Django 3.2.9 on 2021-11-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('clothes', '0004_auto_20211130_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes_brand', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='clothesimage',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_image', to='clothes.clothes'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
