# Generated by Django 3.2.9 on 2021-11-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20211130_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='like',
        ),
    ]
